# Generated by Django 5.2.7 on 2025-11-01 02:20

import backend.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=backend.users.models.upload_to),
        ),
    ]
