# Generated by Django 5.2.7 on 2025-10-31 13:13

import django.db.models.deletion
import django.db.models.functions.text
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, default='Untitled', max_length=128, verbose_name='Document Title')),
                ('slug', models.CharField(blank=True, default='untitled', max_length=128, verbose_name='Document Slug')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('date_modified', models.DateTimeField(auto_now=True, verbose_name='')),
                ('is_public', models.BooleanField(default=False, verbose_name='')),
                ('owner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'indexes': [models.Index(fields=['title'], name='title_idx'), models.Index(django.db.models.functions.text.Lower('title'), name='title_lower_idx'), models.Index(fields=['slug'], name='slug_idx'), models.Index(django.db.models.functions.text.Lower('slug'), name='slug_lower_idx')],
            },
        ),
    ]
