# Generated by Django 5.2.7 on 2025-10-31 13:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documents',
            name='collaborator',
            field=models.ManyToManyField(blank=True, null=True, related_name='collaborator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together={('owner_id', 'id')},
        ),
    ]
