# Generated by Django 5.2.7 on 2025-11-01 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_documents_collaborator_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documents',
            unique_together=set(),
        ),
    ]
