# Generated by Django 5.2.7 on 2025-10-31 13:13

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_by', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('change_summary', models.TextField(default='', verbose_name='')),
                ('content_delta', django_ckeditor_5.fields.CKEditor5Field(default='')),
                ('version_number', models.CharField(default='1.0', max_length=10, verbose_name='')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document_version', to='documents.documents')),
            ],
            options={
                'indexes': [models.Index(fields=['document_id', 'version_number'], name='document_id_idx')],
            },
        ),
    ]
