# Generated by Django 5.2.7 on 2025-12-06 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document_version', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentversion',
            old_name='document_id',
            new_name='document',
        ),
    ]
