# Generated by Django 5.2.7 on 2025-11-02 12:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document_permission', '0001_initial'),
        ('documents', '0004_alter_documents_collaborator_operation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='documentpermission',
            constraint=models.UniqueConstraint(fields=('docs', 'granted_by', 'user_id'), name='unique_document_permission'),
        ),
    ]
