# Generated by Django 5.2.7 on 2025-10-31 13:13

import django.db.models.deletion
import django.db.models.functions.text
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', django_ckeditor_5.fields.CKEditor5Field(blank=True, default='')),
                ('position', models.IntegerField(blank=True, default=0, verbose_name='')),
                ('status', models.IntegerField(choices=[(1, 'DRAFT'), (2, 'PUBLISHED')], verbose_name='')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='')),
                ('document_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='documents.documents')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['comment'], name='comment_idx'), models.Index(django.db.models.functions.text.Lower('comment'), name='comment_lower_idx')],
            },
        ),
    ]
